import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./app-styles.css";
import { I18nProviderClient } from "@/lib/locales/client";
import { ReactElement } from "react";
import { AppSidebar } from "./components/AppSidebar";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebarUserGroup } from "./components/AppSidebarUserGroup";
import { AppSidebarFooter } from "./components/AppSidebarFooter";
import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fluens-Tree",
  description: "Generated by create next app",
};

export default async function AppLayout({
  params,
  children,
}: {
  params: Promise<{ locale: string }>;
  children: ReactElement;
}) {
  const { locale } = await params;

  return (
    <I18nProviderClient locale={locale}>
      <ThemeProvider>
        <div className={`${geistSans.variable} ${geistMono.variable}`}>
          <SidebarProvider>
            <div className="flex h-dvh w-full">
              <SidebarTrigger className="fixed top-0 left-0 z-20 flex md:hidden items-center justify-center px-2 h-10 w-10 bg-primary/10" />

              <AppSidebar>
                <AppSidebarUserGroup />
                <AppSidebarFooter />
              </AppSidebar>

              {/* Conteúdo principal */}
              <div className="flex-1 h-full w-full relative">{children}</div>
            </div>
          </SidebarProvider>
        </div>
      </ThemeProvider>
    </I18nProviderClient>
  );
}
